import { useMemo } from 'react';
import { SynapticAssignementRule } from '../types';

export function useSynapticAssignementRules(readonly: boolean) {
  return useMemo(() => {
    if (readonly) return DATA.slice(0, 4);
    return DATA.slice(4);
  }, [readonly]);
}

const DATA: SynapticAssignementRule[] = [
  {
    fromSClass: 'EXC',
    toSClass: 'EXC',
    synapticType: 'E2',
    fromHemisphere: null,
    toHemisphere: null,
    fromRegion: null,
    toRegion: null,
    fromMType: null,
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: 'INH',
    synapticType: 'E2_INH',
    fromHemisphere: null,
    toHemisphere: null,
    fromRegion: null,
    toRegion: null,
    fromMType: null,
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'INH',
    toSClass: 'EXC',
    synapticType: 'I2',
    fromHemisphere: null,
    toHemisphere: null,
    fromRegion: null,
    toRegion: null,
    fromMType: null,
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'INH',
    toSClass: 'INH',
    synapticType: 'I2',
    fromHemisphere: null,
    toHemisphere: null,
    fromRegion: null,
    toRegion: null,
    fromMType: null,
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_*PC',
    toMType: 'L4_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_*PC',
    toMType: 'L4_SSC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L4_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L4_SSC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:C',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:C',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_UPC',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_UPC',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:A',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:A',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:B',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:B',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_HPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:*',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-C',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-BPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC-IPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC-BPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6BPC-TPCA',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_BPC',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_UPC',
    toMType: 'L6_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_BPC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_HPC',
    toMType: 'L6_HPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_BP',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_BP',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_DBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_DBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_BTC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_BTC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_MC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_MC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_MC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_MC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_NGC-DA',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_NGC-SA',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NGC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_L1nonNGC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_*AC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_L1nonNGC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L1_*AC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_NBC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'bAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'bIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cNAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_NBC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'bAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'bIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cNAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_SBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_ChC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NBC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'cNAC',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'dSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'cSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'bSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NBC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'cNAC',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'dSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'cSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'bSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I1_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: 'cACint',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_PT',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: 'dNAC',
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6EXC-L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC-L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC-L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I3_L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I3_L6BC',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I1',
    fromHemisphere: 'left',
    toHemisphere: 'left',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_IPC',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L2_TPC:*',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L23PC_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L3_TPC:*',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_*PC',
    toMType: 'L4_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_*PC',
    toMType: 'L4_SSC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L4_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L4_SSC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L2_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L2_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L23PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L3_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:C',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:C',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_UPC',
    toMType: 'L5_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5STPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_UPC',
    toMType: 'L5_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:A',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:A',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:B',
    toMType: 'L5_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L5TTPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L5_TPC:B',
    toMType: 'L5_TPC:B',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L4SS_L6PC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L4_SSC',
    toMType: 'L6_HPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:*',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_diff',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-C',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-BPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC-IPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC-BPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6BPC-TPCA',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_BPC',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_UPC',
    toMType: 'L6_UPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_BPC',
    toMType: 'L6_BPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6PC_same',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_HPC',
    toMType: 'L6_HPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_TPC:A',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_TPC:C',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_IPC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_BP',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_BP',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_DBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_DBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_BTC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_DT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_BTC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_MC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_MC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_MC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_MC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_NGC-DA',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_NGC-SA',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NGC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NGC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_L1nonNGC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L1_*AC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_L1nonNGC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L1_*AC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_NBC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'bAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'bIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_LBC',
    toEType: 'cNAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_NBC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cACint',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'bAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'bIR',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_NBC',
    toEType: 'cNAC',
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_SBC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: 'EXC',
    toSClass: null,
    synapticType: 'E2_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: null,
    toMType: 'L*_ChC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NBC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'cNAC',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'dSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'cSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_LBC',
    toMType: null,
    toEType: null,
    fromEType: 'bSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_NBC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'cNAC',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'dSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'cSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_NBC',
    toMType: null,
    toEType: null,
    fromEType: 'bSTUT',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I3_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I1_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: 'cACint',
  },
  {
    fromSClass: null,
    toSClass: 'EXC',
    synapticType: 'I2_PT',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L*_SBC',
    toMType: null,
    toEType: null,
    fromEType: 'dNAC',
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6EXC-L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_*PC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCA-L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:A',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6TPCC-L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_TPC:C',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'E2_L6IPC-L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_IPC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I3_L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_TPC:*',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I3_L6BC',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_*PC',
    toEType: null,
    fromEType: null,
  },
  {
    fromSClass: null,
    toSClass: null,
    synapticType: 'I1',
    fromHemisphere: 'right',
    toHemisphere: 'right',
    fromRegion: 'SS',
    toRegion: 'SS',
    fromMType: 'L6_[LNS]BC',
    toMType: 'L6_[LNS]BC',
    toEType: null,
    fromEType: null,
  },
];
