include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 6Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 4

default:
  interruptible: true
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - lint
  - build
  - test
  - deploy

eslint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: lint
  script:
    - npm run prettier:check

build:
  stage: build
  script:
    - npm run build
  except:
    - develop
    - main

unit-test:
  stage: test
  script:
    - npm run test:ci

deploy-dev:
  stage: deploy
  extends: .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/dev
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: dev
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
  only:
    - develop

deploy-prod:
  stage: deploy
  extends: .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/prod
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    NEXT_PUBLIC_BASE_PATH: /mmb-beta
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
  only:
    - develop

deploy-test:
  stage: deploy
  extends: .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/test
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: test
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
  except:
    - main
    - develop
  when: manual
