include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml
    ref: add_dockerhub

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_CPU_REQUEST: 2
  KUBERNETES_CPU_LIMIT: 4
  NODE_OPTIONS: --max-old-space-size=4096

default:
  interruptible: true
  image: node:20-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - .next/cache/

stages:
  - lint
  - build
  - test
  - deploy

eslint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: lint
  script:
    - npm run prettier:check

build:
  stage: build
  script:
    - npm run build
  except:
    - develop
    - main

unit-test:
  stage: test
  script:
    - npm run test:ci

.deploy:
  variables:
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi

deploy-bbp-prod:
  stage: deploy
  extends:
    - .deploy
    - .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/prod
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_BASE_PATH: /mmb-beta
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-aws-prod:
  stage: deploy
  extends:
    - .deploy
    - .build-image-using-kaniko-for-dockerhub
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: bluebrain/sbo-core-web-app
    REGISTRY_IMAGE_TAG: latest
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_BASE_PATH: /mmb-beta
    NEXT_PUBLIC_NEXUS_URL: https://sbo-nexus-delta.shapes-registry.org/v1
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    NEXT_PUBLIC_ATLAS_ES_VIEW_ID: https://sbo-nexus-delta.shapes-registry.org/data/bbp/atlas/98e91247-a3f2-4dae-8cfb-9432fc7d84ae
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_NEXUS_URL
      --build-arg=NEXT_PUBLIC_ATLAS_ES_VIEW_ID
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-bbp-dev:
  stage: deploy
  extends:
    - .deploy
    - .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/dev
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: dev
    NEXT_PUBLIC_BASE_PATH: /mmb-beta/dev
    NEXT_PUBLIC_BBS_ML_URL: https://ml.bbs.master.staging.kcp.bbp.epfl.ch
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_BBS_ML_URL
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=CI_COMMIT_SHORT_SHA
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-test:
  stage: deploy
  extends:
    - .deploy
    - .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/test
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: test
    NEXT_PUBLIC_BASE_PATH: /mmb-beta/test
    NEXT_PUBLIC_BBS_ML_URL: https://ml.bbs.master.staging.kcp.bbp.epfl.ch
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_BBS_ML_URL
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=CI_COMMIT_SHORT_SHA
      --build-arg=NODE_OPTIONS
  except:
    - main
    - develop
  when: manual
