include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fastest'
  CACHE_COMPRESSION_LEVEL: 'fastest'
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_CPU_REQUEST: 2
  KUBERNETES_CPU_LIMIT: 4

default:
  interruptible: true
  image: node:21-alpine

.install_packages:
  script: &install_packages
    - npm ci --cache .npm --prefer-offline

.package_cache:
  cache: &package_cache
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull-push

.build_cache:
  cache: &build_cache
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .next/cache
    policy: pull-push

.heavy_job:
  variables:
    KUBERNETES_MEMORY_REQUEST: 4Gi
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_CPU_REQUEST: 3
    NODE_OPTIONS: --max-old-space-size=4096

stages:
  - setup
  - check
  - build
  - deploy

setup:
  stage: setup
  cache:
    <<: *package_cache
    policy: push
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - package-lock.json
  script: *install_packages

eslint:
  stage: check
  cache:
    <<: *package_cache
    policy: pull
  script:
    - *install_packages
    - npm run lint

prettier:
  stage: check
  cache:
    <<: *package_cache
    policy: pull
  script:
    - *install_packages
    - npm run prettier:check

unit-test:
  stage: check
  extends: .heavy_job
  cache:
    <<: *package_cache
    policy: pull
  script:
    - *install_packages
    - npm run test:ci

build:
  stage: check
  extends: .heavy_job
  cache:
    - <<: *package_cache
      policy: pull
    - <<: *build_cache
  script:
    - *install_packages
    - npm run build
  except:
    - develop
    - main

deploy-bbp-prod:
  stage: deploy
  extends:
    - .heavy_job
    - .build-image-using-kaniko
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/prod
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_BASE_PATH: /mmb-beta
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-aws-prod:
  stage: deploy
  extends:
    - .heavy_job
    - .build-image-using-kaniko
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: bluebrain/sbo-core-web-app
    CI_REGISTRY: https://index.docker.io/v1/
    CI_REGISTRY_USER: bbpbuildbot
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD_DOCKERHUB
    REGISTRY_IMAGE_TAG: latest
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_BASE_PATH: /mmb-beta
    NEXT_PUBLIC_NEXUS_URL: https://sbo-nexus-delta.shapes-registry.org/v1
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    NEXT_PUBLIC_BRAIN_REGION_ONTOLOGY_RESOURCE_TAG: v1.14.2
    NEXT_PUBLIC_ATLAS_ES_VIEW_ID: https://bbp.epfl.ch/neurosciencegraph/data/420e53b8-db21-4f70-a534-d799c4b59b5d
    NEXT_PUBLIC_KG_INFERENCE_BASE_URL: https://kg-inference-api.shapes-registry.org
    NEXT_PUBLIC_THUMBNAIL_GENERATION_BASE_URL: https://openbrainplatform.org/api/thumbnail-generation
    NEXT_PUBLIC_VIRTUAL_LAB_API_URL: https://openbrainplatform.org/api/virtual-lab-manager
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_51P6uAFFE4Bi50cLlatJIc0fUPsP0jQkaCCJ8TTkIYOOLIrLzxX1M9p1kVD11drNqsF9p7yiaumWJ8UHb3ptJJRXB00y3qjYReV
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=NEXT_PUBLIC_NEXUS_URL
      --build-arg=NEXT_PUBLIC_ATLAS_ES_VIEW_ID
      --build-arg=NEXT_PUBLIC_KG_INFERENCE_BASE_URL
      --build-arg=NEXT_PUBLIC_THUMBNAIL_GENERATION_BASE_URL
      --build-arg=NEXT_PUBLIC_VIRTUAL_LAB_API_URL
      --build-arg=NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      --build-arg=NEXT_PUBLIC_BRAIN_REGION_ONTOLOGY_RESOURCE_TAG
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-bbp-dev:
  stage: deploy
  extends:
    - .heavy_job
    - .build-image-using-kaniko
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/dev
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: dev
    NEXT_PUBLIC_BASE_PATH: /mmb-beta/dev
    NEXT_PUBLIC_BBS_ML_URL: https://openbrainplatform.org/api/literature/
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_BBS_ML_URL
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=CI_COMMIT_SHORT_SHA
      --build-arg=NODE_OPTIONS
  only:
    - develop

deploy-test:
  stage: deploy
  extends:
    - .heavy_job
    - .build-image-using-kaniko
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/core-web-app
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/core-web-app/test
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    NEXT_PUBLIC_ENVIRONMENT: test
    NEXT_PUBLIC_BASE_PATH: /mmb-beta/test
    NEXT_PUBLIC_BBS_ML_URL: https://openbrainplatform.org/api/literature/
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_BASE_PATH
      --build-arg=NEXT_PUBLIC_BBS_ML_URL
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=CI_COMMIT_SHORT_SHA
      --build-arg=NODE_OPTIONS
  except:
    - main
    - develop
  when: manual
