export default [
  {
    key: 'row-1',
    name: 'Campaign name number one',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.0, 0.0, 0.1],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.0,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-2',
    name: 'Campaign name number two',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.0, 0.1, 0.2],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.1,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-3',
    name: 'Campaign name number three',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.1, 0.2, 0.3],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.2,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-4',
    name: 'Campaign name number four',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.2, 0.3, 0.4],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.3,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-5',
    name: 'Campaign name number five',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.3, 0.4, 0.5],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.4,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-6',
    name: 'Campaign name number six',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.4, 0.5, 0.6],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.5,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-7',
    name: 'Campaign name number seven',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.5, 0.6, 0.7],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.6,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-8',
    name: 'Campaign name number eight',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.6, 0.7, 0.8],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.7,
    startDelay: 1000,
    date: '4 Days Ago',
  },
  {
    key: 'row-9',
    name: 'Campaign name number nine',
    configuration: 'Release 23.01',
    deplStdevMeanRatio: [0.7, 0.8, 0.9],
    ca: [1.05, 1.01],
    vpmPct: 5.0,
    desiredConnectedProportionOfInvivoFrs: 0.8,
    startDelay: 1000,
    date: '4 Days Ago',
  },
];
