export const metadataKeys = [
  '@id',
  '_constrainedBy',
  '_createdAt',
  '_createdBy',
  '_deprecated',
  '_incoming',
  '_outgoing',
  '_project',
  '_rev',
  '_schemaProject',
  '_self',
  '_updatedAt',
  '_updatedBy',
];
