import type { EditorThemeClasses } from 'lexical';

import './app-editor-theme.css';

const theme: EditorThemeClasses = {
  autocomplete: 'app-editor-theme__autocomplete',
  blockCursor: 'app-editor-theme__blockCursor',
  characterLimit: 'app-editor-theme__characterLimit',
  code: 'app-editor-theme__code',
  codeHighlight: {
    atrule: 'app-editor-theme__tokenAttr',
    attr: 'app-editor-theme__tokenAttr',
    boolean: 'app-editor-theme__tokenProperty',
    builtin: 'app-editor-theme__tokenSelector',
    cdata: 'app-editor-theme__tokenComment',
    char: 'app-editor-theme__tokenSelector',
    class: 'app-editor-theme__tokenFunction',
    'class-name': 'app-editor-theme__tokenFunction',
    comment: 'app-editor-theme__tokenComment',
    constant: 'app-editor-theme__tokenProperty',
    deleted: 'app-editor-theme__tokenProperty',
    doctype: 'app-editor-theme__tokenComment',
    entity: 'app-editor-theme__tokenOperator',
    function: 'app-editor-theme__tokenFunction',
    important: 'app-editor-theme__tokenVariable',
    inserted: 'app-editor-theme__tokenSelector',
    keyword: 'app-editor-theme__tokenAttr',
    namespace: 'app-editor-theme__tokenVariable',
    number: 'app-editor-theme__tokenProperty',
    operator: 'app-editor-theme__tokenOperator',
    prolog: 'app-editor-theme__tokenComment',
    property: 'app-editor-theme__tokenProperty',
    punctuation: 'app-editor-theme__tokenPunctuation',
    regex: 'app-editor-theme__tokenVariable',
    selector: 'app-editor-theme__tokenSelector',
    string: 'app-editor-theme__tokenSelector',
    symbol: 'app-editor-theme__tokenProperty',
    tag: 'app-editor-theme__tokenProperty',
    url: 'app-editor-theme__tokenOperator',
    variable: 'app-editor-theme__tokenVariable',
  },
  embedBlock: {
    base: 'app-editor-theme__embedBlock',
    focus: 'app-editor-theme__embedBlockFocus',
  },
  hashtag: 'app-editor-theme__hashtag',
  heading: {
    h1: 'app-editor-theme__h1',
    h2: 'app-editor-theme__h2',
    h3: 'app-editor-theme__h3',
    h4: 'app-editor-theme__h4',
    h5: 'app-editor-theme__h5',
    h6: 'app-editor-theme__h6',
  },
  hr: 'app-editor-theme__hr',
  image: 'editor-image',
  gallery: 'editor-gallery',
  indent: 'app-editor-theme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'app-editor-theme__layoutContainer',
  layoutItem: 'app-editor-theme__layoutItem',
  link: 'app-editor-theme__link',
  list: {
    checklist: 'app-editor-theme__checklist',
    listitem: 'app-editor-theme__listItem',
    listitemChecked: 'app-editor-theme__listItemChecked',
    listitemUnchecked: 'app-editor-theme__listItemUnchecked',
    nested: {
      listitem: 'app-editor-theme__nestedListItem',
    },
    ol: 'app-editor-theme__ol',
    olDepth: [
      'app-editor-theme__ol1',
      'app-editor-theme__ol2',
      'app-editor-theme__ol3',
      'app-editor-theme__ol4',
      'app-editor-theme__ol5',
    ],
    ul: 'app-editor-theme__ul',
    ulDepth: ['app-editor-theme__ul1'],
  },
  ltr: 'app-editor-theme__ltr',
  mark: 'app-editor-theme__mark',
  markOverlap: 'app-editor-theme__markOverlap',
  paragraph: 'app-editor-theme__paragraph',
  quote: 'app-editor-theme__quote',
  rtl: 'app-editor-theme__rtl',
  table: 'app-editor-theme__table',
  tableAddColumns: 'app-editor-theme__tableAddColumns',
  tableAddRows: 'app-editor-theme__tableAddRows',
  tableCell: 'app-editor-theme__tableCell',
  tableCellActionButton: 'app-editor-theme__tableCellActionButton',
  tableCellActionButtonContainer: 'app-editor-theme__tableCellActionButtonContainer',
  tableCellEditing: 'app-editor-theme__tableCellEditing',
  tableCellHeader: 'app-editor-theme__tableCellHeader',
  tableCellPrimarySelected: 'app-editor-theme__tableCellPrimarySelected',
  tableCellResizer: 'app-editor-theme__tableCellResizer',
  tableCellSelected: 'app-editor-theme__tableCellSelected',
  tableCellSortedIndicator: 'app-editor-theme__tableCellSortedIndicator',
  tableResizeRuler: 'app-editor-theme__tableCellResizeRuler',
  tableSelected: 'app-editor-theme__tableSelected',
  tableSelection: 'app-editor-theme__tableSelection',
  text: {
    bold: 'app-editor-theme__textBold',
    code: 'app-editor-theme__textCode',
    italic: 'app-editor-theme__textItalic',
    strikethrough: 'app-editor-theme__textStrikethrough',
    subscript: 'app-editor-theme__textSubscript',
    superscript: 'app-editor-theme__textSuperscript',
    underline: 'app-editor-theme__textUnderline',
    underlineStrikethrough: 'app-editor-theme__textUnderlineStrikethrough',
  },
};

export default theme;
