import { GenericEventInterface } from './utils/generic-event';

export type BraynsColorOpaque = [red: number, green: number, blue: number];
export type BraynsColorTransparent = [red: number, green: number, blue: number, alpha: number];

export type BraynsObjects = Array<BraynsMeshOptions>;

export interface BraynsMeshOptions {
  type: 'mesh';
  url: string;
  color: BraynsColorTransparent;
}

export interface BraynsServiceInterface {
  readonly eventBusy: GenericEventInterface<BusyEventParams>;

  /**
   * Define what canvas will receive the frames generated by Brayns Renderer.
   * It's size will be observed to change the viewport accordingly.
   * Only one canvas can be observed at the time, though.
   */
  canvas: HTMLCanvasElement | null;

  reset(): Promise<void>;

  /**
   * Add a list of objects to the current scene, but remove everything else.
   */
  showOnly(objects: BraynsObjects): void;
}

export interface BusyEventParams {
  type: 'mesh';
  id: string;
  isLoading: boolean;
}
