export const typeToColumns: { [id: string]: string[] } = {
  'https://bbp.epfl.ch/ontologies/core/bmo/ExperimentalBoutonDensity': [
    'brainRegion',
    'mType',
    'meanstd',
    'sem',
    'numberOfMeasurements',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
  'https://bbp.epfl.ch/ontologies/core/bmo/ExperimentalNeuronDensity': [
    'brainRegion',
    'mType',
    'eType',
    'neuronDensity',
    'numberOfMeasurements',
    'name',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
  'https://bbp.epfl.ch/ontologies/core/bmo/ExperimentalTrace': [
    'brainRegion',
    'eType',
    'name',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
  'https://bbp.epfl.ch/ontologies/core/bmo/ExperimentalLayerThickness': [
    'brainRegion',
    'layer',
    'layerThickness',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
  'https://neuroshapes.org/ReconstructedNeuronMorphology': [
    'brainRegion',
    'mType',
    'name',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
  'https://neuroshapes.org/SimulationCampaign': ['simCampName', 'brainConfiguration', 'createdAt'],
  'https://bbp.epfl.ch/ontologies/core/bmo/ExperimentalSynapsesPerConnection': [
    'brainRegion',
    'mType',
    'name',
    'subjectSpecies',
    'contributors',
    'createdAt',
  ],
};
