name: Deploy AWS Prod

env:
  NEXT_PUBLIC_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ vars.SENTRY_AUTH_TOKEN }}

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    env:
      REGISTRY_IMAGE_TAG: 'latest'
      NEXT_PUBLIC_ENVIRONMENT: prod
      NEXT_PUBLIC_BASE_PATH: /mmb-beta
      NEXT_PUBLIC_NEXUS_URL: https://sbo-nexus-delta.shapes-registry.org/v1
      NEXT_PUBLIC_ATLAS_ES_VIEW_ID: https://sbo-nexus-delta.shapes-registry.org/data/bbp/atlas/98e91247-a3f2-4dae-8cfb-9432fc7d84ae
      NEXT_PUBLIC_CELL_COMPOSITION_ID: https://sbo-nexus-delta.shapes-registry.org/data/bbp/atlasdatasetrelease/f3cff4fa-9976-4b6d-b8aa-5fe44ba3878c
      NEXT_PUBLIC_KG_INFERENCE_BASE_URL: https://kg-inference-api.shapes-registry.org
      NEXT_PUBLIC_THUMBNAIL_GENERATION_BASE_URL: https://thumbnail-generation-api.shapes-registry.org
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          file: ./Dockerfile
          username: ${{ vars.BBPBUILDBOT_DOCKERHUB_USER }}
          password: ${{ secrets.BBPBUILDBOT_DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.BBPBUILDBOT_DOCKERHUB_USER }}/${{ vars.CI_REGISTRY_IMAGE }}:${{ env.REGISTRY_IMAGE_TAG }}
